### ISSUE TITLE
unsigned char *get_file(const char *dir)

### ISSUE THREAD

**Issue by xakepp35** [FlorisCreyf/mp3-decoder#1]
problem - cannot get length of buffer
you are using std::ifstream, why not use std::vector or std::string?

Also, such a mix is a sign of error-prone code style.
you may easily forget delete[] operator.

Do it modern way!
here is replacement version, 4 lines of code, each does bunch of things
Logic is extremely clear:
    1. open file
    2. create buffer
    3. read file to buffer
    4 return it

std::string get_file(const std::string& fileName) {
	std::ifstream dataFile(dir, std::ios::in | std::ios::binary | std::ios::ate);
	std::string dataBuffer(dataFile.tellg(),0); 
	dataFile.seekg(0, std::ios::beg).read(&dataBuffer[0], dataBuffer.size());
	return std::move( dataBuffer );
}

**Comment by FlorisCreyf** [comment]
I changed the code to replace `new` with `std::vector<unsigned char>`. Hopefully that's better.

On a side note, it is important that the buffer is an array of unsigned characters to avoid arithmetic shifts.
