### ISSUE TITLE
Failure to Consider CRC Bit in Call to set_side_info in Line 55 of init_frame_params

### ISSUE THREAD

**Issue by vmaddur** [FlorisCreyf/mp3-decoder#4]
The offending line is

`set_side_info(&buffer[4]);`

which fails to consider the case in which the CRC bit is 0, which would make the index 6 instead of 4.

**Comment by FlorisCreyf** [comment]
Thanks. I changed the statement to: `set_side_info(&buffer[crc == 0 ? 6 : 4]);`.
